# Generated by Django 5.2.13 on 2026-05-02 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3C', '0002_cliente_restaurante_remove_platillo_idelemento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platillo',
            name='IDelemento',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='platillo',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='platillo',
            name='restaurante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platillos', to='app3C.restaurante'),
        ),
    ]
