# Generated by Django 5.2.13 on 2026-05-02 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3C', '0003_platillo_idelemento_alter_platillo_precio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platillo',
            name='nombre',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='platillo',
            name='restaurante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='platillos', to='app3C.restaurante'),
        ),
    ]
