# Generated by Django 5.2.13 on 2026-05-02 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3C', '0004_alter_platillo_nombre_alter_platillo_restaurante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platillo',
            name='IDelemento',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='platillo',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='platillos/'),
        ),
        migrations.AlterField(
            model_name='platillo',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='platillo',
            name='restaurante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platillos', to='app3C.restaurante'),
        ),
    ]
