# Generated by Django 5.2.13 on 2026-05-02 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3C', '0005_alter_platillo_idelemento_alter_platillo_imagen_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='contraseña',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='correo',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='teléfono',
        ),
        migrations.RemoveField(
            model_name='repartidor',
            name='contraseña',
        ),
        migrations.RemoveField(
            model_name='repartidor',
            name='correo',
        ),
        migrations.RemoveField(
            model_name='repartidor',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='repartidor',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='repartidor',
            name='teléfono',
        ),
        migrations.RemoveField(
            model_name='restaurante',
            name='contraseña',
        ),
        migrations.RemoveField(
            model_name='restaurante',
            name='correo',
        ),
        migrations.RemoveField(
            model_name='restaurante',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='restaurante',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='restaurante',
            name='teléfono',
        ),
        migrations.AddField(
            model_name='cliente',
            name='cuenta',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app3C.cuenta'),
        ),
        migrations.AddField(
            model_name='repartidor',
            name='cuenta',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app3C.cuenta'),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='cuenta',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app3C.cuenta'),
        ),
    ]
