# Generated by Django 5.2.14 on 2026-05-12 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3C', '0006_remove_cliente_contraseña_remove_cliente_correo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='cuenta',
        ),
        migrations.RemoveField(
            model_name='repartidor',
            name='cuenta',
        ),
        migrations.RemoveField(
            model_name='restaurante',
            name='cuenta',
        ),
        migrations.AddField(
            model_name='cliente',
            name='contraseña',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='cliente',
            name='correo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='cliente',
            name='teléfono',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='repartidor',
            name='contraseña',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='repartidor',
            name='correo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='repartidor',
            name='direccion',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='repartidor',
            name='nombre',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='repartidor',
            name='teléfono',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='CURP',
            field=models.CharField(blank=True, max_length=18),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='contraseña',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='correo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='nombre',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='teléfono',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='usuario',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='teléfono',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='platillo',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='color',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='modelo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='placa',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='tipo',
            field=models.CharField(max_length=25),
        ),
    ]
