# Generated by Django 5.2.14 on 2026-05-12 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3C', '0007_remove_cliente_cuenta_remove_repartidor_cuenta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='contraseña',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='correo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='teléfono',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='repartidor',
            name='contraseña',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='repartidor',
            name='correo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='repartidor',
            name='direccion',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='repartidor',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='repartidor',
            name='teléfono',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='restaurante',
            name='CURP',
            field=models.CharField(max_length=18),
        ),
        migrations.AlterField(
            model_name='restaurante',
            name='contraseña',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='restaurante',
            name='correo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='restaurante',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='restaurante',
            name='teléfono',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='restaurante',
            name='usuario',
            field=models.CharField(max_length=50),
        ),
    ]
