# Generated by Django 5.2.14 on 2026-06-08 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3C', '0008_alter_cliente_contraseña_alter_cliente_correo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='contraseña',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='correo',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='teléfono',
        ),
        migrations.RemoveField(
            model_name='cuenta',
            name='CURP',
        ),
        migrations.RemoveField(
            model_name='cuenta',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='repartidor',
            name='contraseña',
        ),
        migrations.RemoveField(
            model_name='repartidor',
            name='correo',
        ),
        migrations.RemoveField(
            model_name='repartidor',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='repartidor',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='repartidor',
            name='teléfono',
        ),
        migrations.RemoveField(
            model_name='restaurante',
            name='CURP',
        ),
        migrations.RemoveField(
            model_name='restaurante',
            name='contraseña',
        ),
        migrations.RemoveField(
            model_name='restaurante',
            name='correo',
        ),
        migrations.RemoveField(
            model_name='restaurante',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='restaurante',
            name='teléfono',
        ),
        migrations.RemoveField(
            model_name='restaurante',
            name='usuario',
        ),
        migrations.AddField(
            model_name='cliente',
            name='IDcuenta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='app3C.cuenta'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='repAsignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='app3C.repartidor'),
        ),
        migrations.AddField(
            model_name='repartidor',
            name='CURP',
            field=models.CharField(default='000000000000000000', max_length=18),
        ),
        migrations.AddField(
            model_name='repartidor',
            name='IDcuenta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='repartidores', to='app3C.cuenta'),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='IDcuenta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='restaurantes', to='app3C.cuenta'),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='direccion',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='propietario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos', to='app3C.repartidor'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='userCliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='app3C.cliente'),
        ),
        migrations.AlterField(
            model_name='platillo',
            name='restaurante',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='platillos', to='app3C.restaurante'),
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tarjetas', to='app3C.cuenta'),
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copias', models.PositiveIntegerField()),
                ('pedido', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ordenes', to='app3C.pedido')),
                ('platillo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ordenes', to='app3C.platillo')),
            ],
        ),
    ]
