# FROM nginx:latest
# Cambiamos a una versión específica de nginx para garantizar la estabilidad y compatibilidad 
#ya que latest puede tener cambios inesperados.

FROM nginx:1.29.5


# Path para servir archivos con Nginx: /usr/share/nginx/html
COPY /src /usr/share/nginx/html  
